### ISSUE TITLE
open a mail in outlook

### ISSUE THREAD

**Issue by beeekey** [ecederstrand/exchangelib#146]
is there any way, that after I searched for a specific mail, I can open it by an id directly in outlook if it is installed? #

**Comment by ecederstrand** [comment]
I don't know if Outlook supports that functionality, sorry.

**Comment by beeekey** [comment]
ty

**Comment by beeekey** [comment]
am I right, that the item_id is the ConversationID from the Outlook model? 

If it would be possible to read out the EntryID of a mail, I could open the it in Outlook.

**Comment by beeekey** [comment]
hmmm, does someone have an idea to convert the EWS Item ID to an EntryID? Just waisted the whole evening ...

**Comment by ecederstrand** [comment]
Apparently, you can get the EntryID via an extended property: https://social.msdn.microsoft.com/Forums/vstudio/en-US/03c38c1b-5d69-4a54-8781-c7c5203ef024/a-shared-id-in-outlook-and-exchange?forum=vsto See the README on how to work with extended properties in exchangelib.

There's also an EWS service to convert IDs between various formats. You could try that instead, if the above doesn't work: https://msdn.microsoft.com/en-us/library/bb799665(EXCHG.140).aspx

**Comment by ecederstrand** [comment]
Maybe this is solved in #161? @SidharthPati, would you be so kind to share the extended property definition for ENTRY_ID that seemed to work for you?

**Comment by beeekey** [comment]
Hmmm, I spent the last weekend to try to implement a method to use the EWS Service to convert the ID's but I wasn't really successfull :-(

On the first look, the solution from #161 @SidharthPati looked very promising.

But, I have from exchangelib the following item_id `AAMkADk0ZjU4ODc1LTY1MzAtNDdhZS04NGU5LTAwYjE2Mzg5NDA1ZABGAAAAAAAZS9Y2rt6uTJgnyUZSiNf0BwC6iam6EuExS4FgbbOF87exAAAAdGVuAAC6iam6EuExS4FgbbOF87exAAAxj5dhAAA=` 

which should give the entryID, according outlook `00000000194BD636AEDEAE4C9827C9465288D7F40700BA89A9BA12E1314B81606DB385F3B7B100000074656E0000BA89A9BA12E1314B81606DB385F3B7B10000318F97610000` 

but if I'm using the solution from #161 I get `0003240039346635383837352D363533302D343761652D383465392D30306231363338393430356400460000000000194BD636AEDEAE4C9827C9465288D7F40700BA89A9BA12E1314B81606DB385F3B7B100000074656E0000BA89A9BA12E1314B81606DB385F3B7B10000318F97610000`

I think I'm missing somewhere a point in de- or encoding ... but I dont get it (Python 2.7):

`def itemid_to_entryid(itemid):
    decoded_val2 = base64.b64decode(itemid)
    hex_val = decoded_val2.encode('hex').upper()
    return hex_val


def entryid_to_itemid(entryid):
    encoded_val = entryid.lower()
    b16 = bytearray(encoded_val.decode('hex'))
    b64 = base64.b64encode(b16)
    return b64
`

**Comment by ecederstrand** [comment]
Did you use an extended property to get the EntryID? Using the MSDN link, I put the following together, but I don't have Outlook installed to test:


```python
class EntryID(ExtendedProperty):
    property_tag = 4095
    property_type = 'Binary'

Message.register('entry_id', EntryID)

m = a.inbox.all()[0]
print(m.item_id)
print(''.join('{:02x}'.format(b) for b in m.entry_id))
```

**Comment by beeekey** [comment]
You Sir, @ecederstrand are just a genious! Thank you!!! This one works perfectly!

I always thought it, while digging deeper into exchangelib, while trying to implement the EWS ConvertID Service, which I was unable to have it finally run (maybe 60% is done, but unfortunately I still don't understand exchangelib so good that it finally worked [I'm still a pyhton somehow a pyhton beginner :-( ])

I only had to change:
`print(''.join('{:02x}'.format(b) for b in m.entry_id))`
to
`print(''.join( [ "%02X" % ord(x) for x in mail2.entry_id ] ).strip())`
because I somehow got:
`ValueError: Unknown format code 'x' for object of type 'str'` in Pyhton 2.7

Thank you very much for exchangelib and thank you very much for your very fast and exciting support!

Kind regards
Ben

**Comment by ecederstrand** [comment]
I'm glad you finally got it working :-)

**Comment by SidharthPati** [comment]
Sorry @ecederstrand  and @beeekey , I was away for a couple of days. and hence could not respond. 
I'm **fetching the item_id using exchangelib** and then converting it using the above mentioned snippet:

```
import base64
decoded_val = base64.b64decode('AAAAAJXv2ELfyfpHrdn/Vdi/WDYHABw3W1WVDPZHvff3PMvZMf0AAAAWtcAAABw3W1WVDPZHvff3PMvZMf0AABZPjGQAAA==')
print (''.join([ "%02X" % ord(x) for x in decoded_val]).strip())
```
```
OUTPUT:
0000000095EFD842DFC9FA47ADD9FF55D8BF583607001C375B55950CF647BDF7F73CCBD931FD00000016B5C000001C375B55950CF647BDF7F73CCBD931FD0000164F8C640000
```

Thanks again @ecederstrand and @beeekey

**Comment by msheltongit** [comment]
Thanks so much @SidharthPati and @ecederstrand and @beeekey!
This worked for me:
```
#How to save an email as a .msg
import exchangelib
from exchangelib import Credentials, Account, ExtendedProperty, Message
import win32com

class EntryID(ExtendedProperty):
    property_tag = 4095
    property_type = 'Binary'

try:
    #FIND THE EMAIL USING EXCHANGELIB
    credentials = Credentials('email@email.email', 'password')
    a = Account('email@email.email', credentials=credentials, autodiscover=True)
    a.root.refresh()
    a.public_folders_root.refresh()
    a.archive_root.refresh()
    
    Message.register('eid', EntryID)
    
    m = a.inbox.all()[0]
    print ('Subject: ' + m.subject)
    print ('ID: ' + m.id)
    print ('Entry ID: ' + str(m.eid))
    print((''.join('{:02x}'.format(b) for b in m.eid).upper().strip()))
    entryID = ((''.join('{:02x}'.format(b) for b in m.eid).upper().strip()))
except:
    pass

Message.deregister('eid')

#SAVE AS AN OUTLOOK MESSAGE
try:
    outlook = win32com.client.Dispatch("Outlook.Application")
    ns = outlook.GetNamespace("MAPI")
    email = outlook.Session.GetItemFromID(entryID)
    email.saveas('c:/test.msg')
except:
    pass

```
