### ISSUE TITLE
ValueError on MeetingRequest.accept()

### ISSUE THREAD

**Issue by alorence** [ecederstrand/exchangelib#886]
**Describe the bug**
I have an incoming MeetingRequest in the Inbox folder. When calling `accept()` method, I get a ValueError exception. The meeting is correctly accepted on server, and the answer is correctly returned to organizer, but exchangelib fail to parse server response.

**To Reproduce**
Here is a sample of the code I use:

```python
for msg in ews.account.inbox.filter(is_read=False):
    if isinstance(msg, MeetingRequest):
        msg.accept()
```

**Expected behavior**
Meeting is accepted, no exception raised

**Log output**
I obfuscated some irrelevant information (paths on my machine) but the real traceback is the following

```bash
Traceback (most recent call last):
  File "~/path/to/venv/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "~/dev/project-path/core/scheduling.py", line 223, in answer_to_requests
    msg.accept()
  File "~/path/to/venv/exchangelib/items/calendar_item.py", line 39, in accept
    **kwargs
  File "~/path/to/venv/exchangelib/util.py", line 39, in wrapper
    return f(self, *args, **kwargs)
  File "~/path/to/venv/exchangelib/items/calendar_item.py", line 398, in send
    send_meeting_invitations=SEND_TO_NONE,
  File "~/path/to/venv/exchangelib/services/common.py", line 130, in get
    raise ValueError('Expected result length 1, but got %r' % res)
ValueError: Expected result length 1, but got [BulkCreateResult(_id=ItemId(id='AQMkAG...AITfwAAAA==', changekey='DwAAABY.....AACRb'), attachments=[]), BulkCreateResult(_id=ItemId(id='AQMkAGJmMTQxNT.....AAIjqwAAAA==', changekey='CwAAABYAAACnY....AAAAACRx'), attachments=[])]
```

**Additional context**
Python 3.7.4
Exchangelib 4.0.0

I think the issue may come from `exchangelib/services/common.py`:

```python
    def get(self, expect_result=True, **kwargs):
        """Like .call(), but expects exactly one result from the server, or zero when expect_result=False, or either
        zero or one when expect_result=None. Returns either one object or None.

        :param expect_result: None, True, or False
        :param kwargs: Same as arguments for .call()
        :return: Same as .call(), but returns either None or exactly one item
        """
        res = list(self.call(**kwargs))
        if expect_result is None and not res:
            # Allow empty result
            return
        if expect_result is False:
            if res:
                raise ValueError('Expected result length 0, but got %r' % res)
            return
        if len(res) != 1:
            raise ValueError('Expected result length 1, but got %r' % res)
        if isinstance(res[0], Exception):
            raise res[0]
        return res[0]
```

#860 issue was fixed with cf7683e, but I think the response expected length is now too restrictive. Unfortunately, I cannot say why our Exchange server send a response with 2 different `BulkCreateResult` instances, and I don't know if it is a normal behavior or not.

**Comment by ecederstrand** [comment]
Hmm. This is weird. We call the `CreateItem` with one `AcceptItem` item, and the server responds with two IDs. We expect `CreateItem` to return at most one ID.

Can you find out what these two IDs reference? Something like `account.root.get(id=..)` on the two IDs should give you a hint.

The obvious fix is to relax the check in this case, but I'd like to understand what's going on first.

**Comment by alorence** [comment]
Ok, following your advice, I found that result IDs correspond to 
1. The CalendarItem created automatically in account calendar
2. A MeetingRequest instance with same data than the original message I called `accept()` on, but with minor change on the ID.

I think the MeetingRequest is the same than the received request, but I can see the `response_type` field changed from 'NoResponseReceived' to 'Accept' which is perfectly understandable. I think this field update caused the update on ID.

**Comment by ecederstrand** [comment]
The referenced commit should fix the exception. It's still up to you what to do with the returned IDs, we just don't require a single ID from th server anymore.

**Comment by alorence** [comment]
Thank you very much. I will try with the next release !

**Comment by ecederstrand** [comment]
It would be great if you could test this before I roll the next release to make sure it's fixed. The test suite cannot cover this area because the tests only have one account available, any you need at least two to test meeting invitations.

You can install the latest code from GitHub with `pip install git+https://github.com/ecederstrand/exchangelib.git`

**Comment by alorence** [comment]
I just tested with the current master, and I don't see the error anymore when accepting a MeetingRequest. Thank you very much

**Comment by Boodbarbak** [comment]
Hey there.
It seems this issue is back since 4.7.0 . 
https://github.com/ecederstrand/exchangelib/commit/555218ab597ba68e0242e9f42f63daa8548e0edd most likely to be involved as it reverts back https://github.com/ecederstrand/exchangelib/commit/b1f2f68da3230eb80f9ebcea0659ae5376447f6c

**Comment by ecederstrand** [comment]
Thanks for the heads-up! I even managed to ignore my own comment when reverting that commit...

The test suite didn't catch this because it only has access to a single account and therefore can't test meeting invites.
